### ISSUE TITLE
Handling removed notes

### ISSUE THREAD

**Issue by RicoElectrico** [ENT8R/notesreview-api#1]
OSM moderators can remove notes that are clearly spam, or otherwise inappropriate. This operation (compared to closing/reopenning/commenting) will not appear in any RSS feed and querying API for the note will return 404.

Currently NotesReview backend doesn't handle this which causes desync - they are still present on NotesReview despite being gone from osm.org or API. These notes are not present in the subsequent daily note dumps - this is the best way of detecting all the hidden notes (compared to querying all >1M notes to check for 404).

**Comment by ENT8R** [comment]
Theoretically possible and definitely a good suggestion, the only thing which keeps me from syncing the database with the notes dump is that hidden comments are not excluded from the notes dump yet. I already opened a bug report and a pull request to change this.
Syncing the database with the notes dump currently would theoretically remove hidden notes, but include hidden comments of a note and I am sure that either behavior is not wanted, so I would like to wait for this being fixed in the source of the data.

**Comment by danieldegroot2** [comment]
Was https://github.com/openstreetmap/planet-notes-dump/pull/1

@ENT8R Can still see bunch of removed notes from past month. [Example](https://ent8r.github.io/NotesReview/?view=map&map=13%2F52.6628%2F-8.637&bbox=-8.7468%2C52.6360%2C-8.5271%2C52.6896&area=view&anonymous=only)
(I don't know how often there is a notes dump, but based on this it is monthly, not hourly/daily/weekly?)

**Comment by ENT8R** [comment]
The notes dump is generated daily, but I only (manually) import it every few months or so, as the import process is not fully automated (yet). See also the following FAQ entry:

> ### Why do some notes appear to be outdated?

> All notes are synchronized every 5 minutes with the OpenStreetMap API. It can happen that notes or comments which have been hidden by the moderators still appear in the results.
This is mainly due to the fact that the underlying API of OpenStreetMap does not directly offer the possibility to know which notes and comments have been hidden by moderators. As a result, the complete notes dump is analyzed from time to time in irregular intervals in order to find and fix these anomalies.
If you want to know the last time the manual synchronization was performed, take a look at the <a href="https://notesreview.kongruent.xyz/api/status" target="_blank" rel="noopener">status page</a> with regard to the value of <code>last_import</code> (for comments) or <code>last_sync</code> (for notes).
